{% set name = "rpfits" %}
{% set version = "2.24" %}
{% set sha256 = "b305ebcc6b36c543f5921f3370f978e660a1ef033a94b0e8159a551eaefeeb5c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: ftp://ftp.atnf.csiro.au/pub/software/rpfits/rpfits-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1003
  detect_binary_files_with_prefix: true
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}

test:
  commands:
    - rpfex </dev/null
    - test -f $PREFIX/lib/librpfits$SHLIB_EXT  # [linux]

about:
  home: http://www.atnf.csiro.au/computing/software/rpfits.html
  license: CSIRO Open Source Software Agreement (GPLv3+)
  license_family: GPL
  license_file: COPYING
  summary: 'Library for reading and writing a FITS-like data format'

extra:
  recipe-maintainers:
    - pkgw
