{% set name = "rpfits" %}
{% set version = "2.24" %}
{% set sha256 = "fe25759fb1093e327cdf04739dc30e0f3193c21e2b44deb7ead62d335bd54b25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://newton.cx/~peter/files/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  detect_binary_files_with_prefix: true
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - libgfortran-ng >=3.0  # [osx]
    - libgfortran-ng >=4.9  # [linux]
  run:

test:
  commands:
    - rpfex </dev/null
    - test -f $PREFIX/lib/librpfits.so  # [linux]
    - test -f $PREFIX/lib/librpfits.dylib  # [osx]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.atnf.csiro.au/computing/software/rpfits.html
  license: CSIRO Open Source Software Agreement (GPLv3+)
  license_family: GPL
  license_file: COPYING
  summary: 'Library for reading and writing a FITS-like data format'

extra:
  recipe-maintainers:
    - pkgw
