travis:
  secure:
    BINSTAR_TOKEN: hLRf6lDUnomPbZn/mqcVaQM0W0eawhl7dj71QNw00YzSN2w5n6w6PksHaDypds+B/06JoGGPLB2V1A6c+IBWjU16IkuxjgF7HH6mqLl2Hxq0WKTNTw7XLo+b16Whn6kUv8iixFF/+QXw9PA+C3nt+vLPTVrsmBX2oZFA6B2TJl1EBfQ3S6KqMKoVYq+XSaSEWhj8cr6CbptlZFyMMO38NIqkJ0vHnOc5ZkezpNafotx5e8NBJVJlh1hI85Fc987UK6RyxTIFqNfbslL8x3hbSB3RbmbqLUjRFutvb/onXJst8owCFkuxii+hGZRua6AvZQGHPOQ9U93Tb00xAz3U2E04PORXv8ttLql6NMmoKzjPl8DpeSNKb0TfcW65ufkNty3i9le3ulDnZyrbx/GHaR+c/ncK9xKVTEB8GdVflD3/nMycdRcNRTIaPbEi/p4IZ5iCsTsix2/NHxyJ0ckEqX880KIihG7thKX12XfsCHcKwGWNqJzPJzg68KZENZ2sAuUSpt61DbFOOxmbJJPuh9+xMvMpdtYl3EYDjGnvs0o+U9KGmOb6K/nq+Tjwl4aVpoOlaFy9+nPjB8nwd6uC6rg8m0pPNylswcpTwcXWql8ZthDCEEafPsT9QK57rJMbm9H71l8EiGZ+DRxFuzG+6b2DvVfgZbu+ngo7sVafVoc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
