appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RtAkCYybt2WBkr54/gkLTcZLZ9IQSiuP7zJ3aCpmnpOwgLsDkgZjwfbMwH9ru6QRyznwY+0b6JepOidkcFkUy+LqY2oJsgDh/xwkmtPwLXekGGarzUnjobBP2QvRXS++2UVR+eeQp+nhg0t87K6+X59Z79ABZV+gp1kB+GBZxiBRvWrzBw88G9DMTuNfZVIvsSrL9EW9JW7sC4uqFW4PiuEmGqwVxNV7VS2Em7ziTcqjQo2OQ6CgF8YSMRT4U6ELvMU8+qlvGMCb+YJ5RP34FdMl0I37hoUKm7hibX4H5HvegVQh/f5/46sKktYvx5OlYNQoC0dMxOH10VHdsL3fs1U086gyrU2Eft1ezTz4/ro1GY7MT0J34G89YJ83uAwqXgBIUuj8sPOHeqm4T7OGvfOZHsXxSJJ+9MKW82xMhNpX6z8iouMJolgUBWjapvcHCqpODIyopTHpgDcHhazKcWABmuWk99PMWddWxpA2L+9yA5uh2lRDTCv9NLQQn8/Sv7VBQrhZfGerITJLAWsfFTmOWYaceDtWscV1RIlski2a0d2D9JU/fqeVYE3XGDMkUAxZONAK+qu+d4SiWi9a1UCpx+ItGsOzQXPhc4d64K6TnxmtVRFjeKw89dqnrz4K4psS+8UfPSFyPvAsZ0MnB1vklgY8a+d5CTL7oRYscAk=}
